.TH "leet::Room::Room" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leet::Room::Room \- Class which represents a single room, along with its properties\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libleet\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBroomID\fP"
.br
.ti -1c
.RI "std::string \fBroomType\fP"
.br
.ti -1c
.RI "std::string \fBName\fP"
.br
.ti -1c
.RI "std::string \fBavatarURL\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBguestCanJoin\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBworldReadable\fP"
.br
.ti -1c
.RI "std::string \fBAlias\fP"
.br
.ti -1c
.RI "std::string \fBTopic\fP"
.br
.ti -1c
.RI "std::string \fBjoinRule\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmemberCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class which represents a single room, along with its properties\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::string leet::Room::Room::Alias"

.SS "std::string leet::Room::Room::avatarURL"

.SS "\fBbool\fP leet::Room::Room::guestCanJoin"

.SS "std::string leet::Room::Room::joinRule"

.SS "\fBint\fP leet::Room::Room::memberCount"

.SS "std::string leet::Room::Room::Name"

.SS "std::string leet::Room::Room::roomID"

.SS "std::string leet::Room::Room::roomType"

.SS "std::string leet::Room::Room::Topic"

.SS "\fBbool\fP leet::Room::Room::worldReadable"


.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
