.TH "leet::Filter" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leet::Filter
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFilter\fP"
.br
.RI "\fBFilter\fP, can be used to find an event ID by functions that make use of it\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
