.TH "leet::Sync::userEvent" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leet::Sync::userEvent \- Class that represents a user event\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libleet\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBuserID\fP"
.br
.ti -1c
.RI "std::string \fBavatarURL\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBcurrentlyActive\fP"
.br
.ti -1c
.RI "\fBint\fP \fBlastActiveAgo\fP"
.br
.ti -1c
.RI "std::string \fBPresence\fP"
.br
.ti -1c
.RI "std::string \fBstatusMessage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class that represents a user event\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::string leet::Sync::userEvent::avatarURL"

.SS "\fBbool\fP leet::Sync::userEvent::currentlyActive"

.SS "\fBint\fP leet::Sync::userEvent::lastActiveAgo"

.SS "std::string leet::Sync::userEvent::Presence"

.SS "std::string leet::Sync::userEvent::statusMessage"

.SS "std::string leet::Sync::userEvent::userID"


.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
