.TH "leet::Sync" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leet::Sync
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBinviteEvent\fP"
.br
.RI "Class that represents an invite event\&. "
.ti -1c
.RI "class \fBmegolmSession\fP"
.br
.RI "Class that represents a Megolm session sent in the room\&. "
.ti -1c
.RI "class \fBnameEvent\fP"
.br
.RI "Class that represents a name event\&. "
.ti -1c
.RI "class \fBSync\fP"
.br
.RI "Class containing objects of all the other classes in \fBleet::Sync\fP\&. "
.ti -1c
.RI "class \fBuserEvent\fP"
.br
.RI "Class that represents a user event\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
