.TH "leet::VOIP" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leet::VOIP
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCredentials\fP"
.br
.RI "Class which represents TURN server credentials returned\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
