.TH "leet::User::Profile" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leet::User::Profile \- Class which represents a user profile, along with his or her devices\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libleet\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBuserID\fP"
.br
.ti -1c
.RI "std::string \fBdisplayName\fP"
.br
.ti -1c
.RI "std::string \fBavatarURL\fP"
.br
.ti -1c
.RI "std::vector< \fBUser::Device\fP > \fBDevices\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class which represents a user profile, along with his or her devices\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::string leet::User::Profile::avatarURL"

.SS "std::vector<\fBUser::Device\fP> leet::User::Profile::Devices"

.SS "std::string leet::User::Profile::displayName"

.SS "std::string leet::User::Profile::userID"


.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
