.TH "leetCrypto::randomBytes" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leetCrypto::randomBytes \- Class used to generate random bytes\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libleet\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrandomBytes\fP (size_t \fBlength\fP)"
.br
.ti -1c
.RI "\fB~randomBytes\fP ()"
.br
.ti -1c
.RI "size_t \fBlength\fP () const"
.br
.ti -1c
.RI "void * \fBdata\fP () const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fB_data\fP"
.br
.ti -1c
.RI "size_t \fB_length\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class used to generate random bytes\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "leetCrypto::randomBytes::randomBytes (size_t length)\fC [inline]\fP"

.SS "leetCrypto::randomBytes::~randomBytes ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void * leetCrypto::randomBytes::data () const\fC [inline]\fP"

.SS "size_t leetCrypto::randomBytes::length () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "void* leetCrypto::randomBytes::_data"

.SS "size_t leetCrypto::randomBytes::_length"


.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
