.TH "leet::User::Device" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leet::User::Device \- Class which represents a single device for a user\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libleet\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBuserID\fP"
.br
.ti -1c
.RI "std::string \fBdeviceID\fP"
.br
.ti -1c
.RI "std::string \fBcurve25519Key\fP"
.br
.ti -1c
.RI "std::string \fBed25519Key\fP"
.br
.ti -1c
.RI "std::string \fBed25519Signature\fP"
.br
.ti -1c
.RI "std::string \fBdeviceDisplayName\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBolm\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBmegolm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class which represents a single device for a user\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::string leet::User::Device::curve25519Key"

.SS "std::string leet::User::Device::deviceDisplayName"

.SS "std::string leet::User::Device::deviceID"

.SS "std::string leet::User::Device::ed25519Key"

.SS "std::string leet::User::Device::ed25519Signature"

.SS "\fBbool\fP leet::User::Device::megolm"

.SS "\fBbool\fP leet::User::Device::olm"

.SS "std::string leet::User::Device::userID"


.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
