.TH "leet::Room::RoomConfiguration" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leet::Room::RoomConfiguration \- Class which represents settings for a single room that should be created\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libleet\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBFederate\fP {\fBfalse\fP}"
.br
.ti -1c
.RI "\fBbool\fP \fBdirectMessage\fP {\fBfalse\fP}"
.br
.ti -1c
.RI "\fBint\fP \fBPreset\fP {\fBLEET_PRESET_PRIVATE\fP}"
.br
.ti -1c
.RI "std::string \fBName\fP"
.br
.ti -1c
.RI "std::string \fBAlias\fP"
.br
.ti -1c
.RI "std::string \fBTopic\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class which represents settings for a single room that should be created\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::string leet::Room::RoomConfiguration::Alias"

.SS "\fBbool\fP leet::Room::RoomConfiguration::directMessage {\fBfalse\fP}"

.SS "\fBbool\fP leet::Room::RoomConfiguration::Federate {\fBfalse\fP}"

.SS "std::string leet::Room::RoomConfiguration::Name"

.SS "\fBint\fP leet::Room::RoomConfiguration::Preset {\fBLEET_PRESET_PRIVATE\fP}"

.SS "std::string leet::Room::RoomConfiguration::Topic"


.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
