.TH "leet::User" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leet::User
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCredentials\fP"
.br
.RI "\fBCredentials\fP class which contains fields passed to login requests\&. "
.ti -1c
.RI "class \fBCredentialsResponse\fP"
.br
.RI "Class which contains the response from the Matrix homeserver on initial login\&. "
.ti -1c
.RI "class \fBDevice\fP"
.br
.RI "Class which represents a single device for a user\&. "
.ti -1c
.RI "class \fBProfile\fP"
.br
.RI "Class which represents a user profile, along with his or her devices\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
