.TH "leet::Attachment::Attachment" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leet::Attachment::Attachment \- Class which represents an uploaded attachment\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libleet\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBURL\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class which represents an uploaded attachment\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::string leet::Attachment::Attachment::URL"


.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
