.TH "leetCrypto" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leetCrypto
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrandomBytes\fP"
.br
.RI "Class used to generate random bytes\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfillWithRandomBytes\fP (void *_data, size_t _length)"
.br
.RI "Simply fills a buffer with random bytes\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void leetCrypto::fillWithRandomBytes (void * _data, size_t _length)\fC [inline]\fP"

.PP
Simply fills a buffer with random bytes\&. 
.PP
\fBReturns\fP
.RS 4
void 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
