.TH "leet::Sync::megolmSession" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leet::Sync::megolmSession \- Class that represents a Megolm session sent in the room\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libleet\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBAlgorithm\fP"
.br
.ti -1c
.RI "std::string \fBcipherText\fP"
.br
.ti -1c
.RI "\fBint\fP \fBcipherType\fP"
.br
.ti -1c
.RI "std::string \fBsenderKey\fP"
.br
.ti -1c
.RI "std::string \fBSender\fP"
.br
.ti -1c
.RI "std::string \fBType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class that represents a Megolm session sent in the room\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::string leet::Sync::megolmSession::Algorithm"

.SS "std::string leet::Sync::megolmSession::cipherText"

.SS "\fBint\fP leet::Sync::megolmSession::cipherType"

.SS "std::string leet::Sync::megolmSession::Sender"

.SS "std::string leet::Sync::megolmSession::senderKey"

.SS "std::string leet::Sync::megolmSession::Type"


.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
