.TH "leet::Event::Event" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leet::Event::Event \- Class that represents a generic event not covered by another class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libleet\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBeventID\fP"
.br
.ti -1c
.RI "\fBint32_t\fP \fBAge\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class that represents a generic event not covered by another class\&. 

Class that represents a generic event not covered by another class\&. It doesn't do much and only provides the event ID and time stamp so it can be used with invokeRequest for example\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBint32_t\fP leet::Event::Event::Age"

.SS "std::string leet::Event::Event::eventID"


.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
