.TH "leet::Message::Message" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leet::Message::Message \- Class which represents a single message, along with its properties\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libleet\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBmessageText\fP"
.br
.ti -1c
.RI "std::string \fBformattedText\fP"
.br
.ti -1c
.RI "std::string \fBFormat\fP"
.br
.ti -1c
.RI "std::string \fBType\fP"
.br
.ti -1c
.RI "std::string \fBmessageType\fP"
.br
.ti -1c
.RI "std::string \fBeventID\fP"
.br
.ti -1c
.RI "std::string \fBSender\fP"
.br
.ti -1c
.RI "std::string \fBmimeType\fP"
.br
.ti -1c
.RI "\fBint32_t\fP \fBAge\fP"
.br
.ti -1c
.RI "\fBint\fP \fBattachmentWidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBattachmentHeight\fP"
.br
.ti -1c
.RI "\fBint\fP \fBattachmentSize\fP"
.br
.ti -1c
.RI "\fBint\fP \fBattachmentLength\fP"
.br
.ti -1c
.RI "std::string \fBattachmentURL\fP"
.br
.ti -1c
.RI "\fBint\fP \fBthumbnailWidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBthumbnailHeight\fP"
.br
.ti -1c
.RI "\fBint\fP \fBthumbnailSize\fP"
.br
.ti -1c
.RI "std::string \fBthumbnailMimeType\fP"
.br
.ti -1c
.RI "std::string \fBthumbnailURL\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBEncrypted\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBmegolm\fP"
.br
.ti -1c
.RI "std::string \fBcipherText\fP"
.br
.ti -1c
.RI "std::string \fBsenderKey\fP"
.br
.ti -1c
.RI "std::string \fBsessionID\fP"
.br
.ti -1c
.RI "std::string \fBdeviceID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class which represents a single message, along with its properties\&. 

This class represents a single message To represent several messages, one might consider using std::vector 
.SH "Member Data Documentation"
.PP 
.SS "\fBint32_t\fP leet::Message::Message::Age"

.SS "\fBint\fP leet::Message::Message::attachmentHeight"

.SS "\fBint\fP leet::Message::Message::attachmentLength"

.SS "\fBint\fP leet::Message::Message::attachmentSize"

.SS "std::string leet::Message::Message::attachmentURL"

.SS "\fBint\fP leet::Message::Message::attachmentWidth"

.SS "std::string leet::Message::Message::cipherText"

.SS "std::string leet::Message::Message::deviceID"

.SS "\fBbool\fP leet::Message::Message::Encrypted"

.SS "std::string leet::Message::Message::eventID"

.SS "std::string leet::Message::Message::Format"

.SS "std::string leet::Message::Message::formattedText"

.SS "\fBbool\fP leet::Message::Message::megolm"

.SS "std::string leet::Message::Message::messageText"

.SS "std::string leet::Message::Message::messageType"

.SS "std::string leet::Message::Message::mimeType"

.SS "std::string leet::Message::Message::Sender"

.SS "std::string leet::Message::Message::senderKey"

.SS "std::string leet::Message::Message::sessionID"

.SS "\fBint\fP leet::Message::Message::thumbnailHeight"

.SS "std::string leet::Message::Message::thumbnailMimeType"

.SS "\fBint\fP leet::Message::Message::thumbnailSize"

.SS "std::string leet::Message::Message::thumbnailURL"

.SS "\fBint\fP leet::Message::Message::thumbnailWidth"

.SS "std::string leet::Message::Message::Type"


.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
