.TH "leet::Event" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leet::Event
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEvent\fP"
.br
.RI "Class that represents a generic event not covered by another class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
