.TH "leet::Sync::Sync" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leet::Sync::Sync \- Class containing objects of all the other classes in \fBleet::Sync\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libleet\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBuserEvent\fP > \fBuserEvents\fP"
.br
.ti -1c
.RI "std::vector< \fBnameEvent\fP > \fBnameEvents\fP"
.br
.ti -1c
.RI "std::vector< \fBinviteEvent\fP > \fBinviteEvents\fP"
.br
.ti -1c
.RI "std::vector< \fBmegolmSession\fP > \fBmegolmSessions\fP"
.br
.ti -1c
.RI "std::string \fBnextBatch\fP"
.br
.ti -1c
.RI "nlohmann::json \fBtheRequest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class containing objects of all the other classes in \fBleet::Sync\fP\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBinviteEvent\fP> leet::Sync::Sync::inviteEvents"

.SS "std::vector<\fBmegolmSession\fP> leet::Sync::Sync::megolmSessions"

.SS "std::vector<\fBnameEvent\fP> leet::Sync::Sync::nameEvents"

.SS "std::string leet::Sync::Sync::nextBatch"

.SS "nlohmann::json leet::Sync::Sync::theRequest"

.SS "std::vector<\fBuserEvent\fP> leet::Sync::Sync::userEvents"


.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
