.TH "leet::Room" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leet::Room
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRoom\fP"
.br
.RI "Class which represents a single room, along with its properties\&. "
.ti -1c
.RI "class \fBRoomConfiguration\fP"
.br
.RI "Class which represents settings for a single room that should be created\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
