.TH "leet::VOIP::Credentials" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leet::VOIP::Credentials \- Class which represents TURN server credentials returned\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libleet\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBUsername\fP"
.br
.ti -1c
.RI "std::string \fBPassword\fP"
.br
.ti -1c
.RI "\fBint\fP \fBtimeToLiveIn\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBURI\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class which represents TURN server credentials returned\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::string leet::VOIP::Credentials::Password"

.SS "\fBint\fP leet::VOIP::Credentials::timeToLiveIn"

.SS "std::vector<std::string> leet::VOIP::Credentials::URI"

.SS "std::string leet::VOIP::Credentials::Username"


.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
