.TH "leet::Sync::nameEvent" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leet::Sync::nameEvent \- Class that represents a name event\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libleet\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBroomID\fP"
.br
.ti -1c
.RI "std::string \fBroomName\fP"
.br
.ti -1c
.RI "std::string \fBInviter\fP"
.br
.ti -1c
.RI "std::string \fBstateKey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class that represents a name event\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::string leet::Sync::nameEvent::Inviter"

.SS "std::string leet::Sync::nameEvent::roomID"

.SS "std::string leet::Sync::nameEvent::roomName"

.SS "std::string leet::Sync::nameEvent::stateKey"


.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
