.TH "leet::Sync::inviteEvent" 3 "Version 0.1" "libleet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leet::Sync::inviteEvent \- Class that represents an invite event\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libleet\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBMembership\fP"
.br
.ti -1c
.RI "std::string \fBInviter\fP"
.br
.ti -1c
.RI "std::string \fBinvitedUser\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class that represents an invite event\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::string leet::Sync::inviteEvent::invitedUser"

.SS "std::string leet::Sync::inviteEvent::Inviter"

.SS "std::string leet::Sync::inviteEvent::Membership"


.SH "Author"
.PP 
Generated automatically by Doxygen for libleet from the source code\&.
